### ISSUE TITLE
Minor change requests

### ISSUE THREAD

**Issue by jn2chang** [mattrebor/emsiweb#332]
This is a continuation of minor changes in EMSIONLINE.org

**Comment by jn2chang** [comment]
1
What's up update request.
Please add the following in What's up:
美東各生命堂暑期聖經班

**Comment by jn2chang** [comment]
2
News update request.
Please add the following news in the Chinese site of News:
美東各生命堂暑期聖經班
7/10 – 14俄備得生命堂暑期聖經班
每天下午一點到五點。詳情請洽楊張秀蘭傳道: (973) 335-7337 ext. 220, (C) (973) 699-3223.
7/17- 21  多華谷生命堂暑期聖經班
每天早上9點到下午1點, 歡迎兒年齡:5-12歲參加。可上網報名: https://towacovbs.myanswers.com/2017/
I will email you the corresponding word document.

**Comment by jn2chang** [comment]
3
“What’s up” change request:
Please add the following in “ What’s up”.
East Coast CEC’s Summer Vacation Bible Schools
This request is the same as Request 314.41 which was not implemented because of the sudden closure of Request 314.

**Comment by jn2chang** [comment]
4
42
“News” change request:
Please add the following in the “News”
East Coast CEC’s Summer Vacation Bible Schools
7/10 – 14 CEMC Oradell VBS
The VBS will be held from 1 pm to 5 pm. To sign up, please call Ev. Sorina Yang at (973) 335-7337 ext. 220, (C) (973) 699-3223.
7/17 -21 CEMC Towaco’s VBS
For children ages 5-12 during the week of 7/17-21 from 9am to 1pm. Registration at https://towacovbs.myanswers.com/2017/.
I will email the word document.
This request is the same as Request 314.42 which was not implemented because of the sudden closure of Request 314.

**Comment by jn2chang** [comment]
5
Completed 7-6-17
What's Up Change Request.
Please remove everything in the English site of "What's Up"", and replace with the following items:
2017 C E C Churches in Netherland Summer Camps
Learn More
8/14-17/2017 C E C Churches in Spain Summer Conference
Learn More
8/28-9/1/2017 C E C Churches in Portugal Summer Youth Conference
Learn More
I shall email you the word document.

**Comment by jn2chang** [comment]
6
"News" update request.
Please add the following in the “News” under   East Coast CEC’s Summer Vacation Bible Schools below news of CEMC Towaco VBS.
8/7-11 CEMC Livingston’s VBS 
For children age’s 5-11 during the week of 8/7-11 from 8:45 am to noon. Registration at https://www.ceclivingston.org/vbs.

**Comment by jn2chang** [comment]
7
"News" update request.
Please add the following to the Chinese site of  “News” under  美東各生命堂暑期聖經班 below news on  多華谷生命堂暑期聖經班
8/7-11  活石園生命堂兒童夏令營
每天早上8:45到中午十二點, 歡迎兒童年齡: 5-11歲參加。可上網報名: https://www.ceclivingston.org/vbs.
I will send you the word document corresponds to this change.

**Comment by jn2chang** [comment]
8
CEC Fuenlabrada in Spain change request.
At the Chinese church landing site and at the English church landing site,  please change the email address to:
emsifuencheng@gmail.com
.

**Comment by jn2chang** [comment]
9
CEC Fuenlabrada in Spain change request.
At the Chinese Contact Us site  and at the English Contact Us site,  please change the email address to:
emsifuencheng@gmail.com

**Comment by emsizionwu** [comment]
吴牧师平安！寄上加纳利亚生命堂的新邮箱地址：emsigrancanaria @yahoo.com


Calle Presidente Alvear  numero 7 Portal 2 local 2. 
35006 Las Palmas

**Comment by jn2chang** [comment]
11

CEC Gran Canaria Change Request:
Please update the address and email address at the Chinese church "Contact Us" site, as well as the English church landing site as below:

Address: Calle Presidente Alvear  numero 7 Portal 2 local 2. 35006 Las Palmas, Gran Canaria, Spain
email：emsigrancanaria @yahoo.com

**Comment by jn2chang** [comment]
12
Please add a church in Portugal. 
馬德拉基督教生命堂
CEC in Madeira

**Comment by jn2chang** [comment]
13
In " Find A Church", at the English site,
1. Please update the total number of churches in Portugal to 7; and the total number of CEC churches to 57.
2. In the Map, please update the total number of churches in Portugal to 7.

**Comment by jn2chang** [comment]
14
In "Find A Church", at the Chinese site,
1. Please update the total number of churches in Portugal to 葡萄牙七間, and the total number of CEC churches to 總共五十七間教會.
2. In the Map, please update the total number of churches in Portugal to 7.

**Comment by jn2chang** [comment]
15 
Please add a church site for CEC Madeira under CEM Portugal.
In the Chinese church landing site please put down the following information:
馬德拉生命堂
地址 : Rua de São Francisco n' 3, 2E  9000-050 FUNCHAL MADEIRA PORTUGAL
電話 : 351-963-333-777
傳真 : 351-218-868-370
電郵:

成立日期: 2016年6月

**Comment by jn2chang** [comment]
16

In the English church landing site for CEC Madeira under CEM Portugal, please put down the following information:
Address : Rua de São Francisco n' 3, 2E 9000-050 FUNCHAL MADEIRA PORTUGAL
Tel.# : 351-963-333-777
Fax# : 351-218-868-370
email:

Established date: June, 2016

**Comment by jn2chang** [comment]
17
In the Chinese Contact Us site for CEC Madeira under CEM Portugal please put down the following information:
馬德拉生命堂
地址 : Rua de São Francisco n' 3, 2E 9000-050 FUNCHAL MADEIRA PORTUGAL
電話 : 351-963-333-777
Google Map showing the location of the church.

**Comment by jn2chang** [comment]
18

In the English Contact Us site for CEC Madeira under CEM Portugal, please put down the following information:
Address : Rua de São Francisco n' 3, 2E 9000-050 FUNCHAL MADEIRA PORTUGAL
Tel.# : 351-963-333-777

**Comment by jn2chang** [comment]
19

Evangelist:  Ev. Chang Yu Zhou, (cell) 351-962-222-221

**Comment by jn2chang** [comment]
20 
CEC Mendelo change request.
At their English church landing site:
1. Please remove the line with their evangelist name and phone #.
2. Please update their address to the following:
Address: Rua B 60Zona Industrial De Arvore Vila Do Conde 4480-622, Portugal
At their Chinese church landing site:
1. Please remove the with with their evangelist's name and phone #.
2. Please update their address to the following:
地址: Rua B 60Zona Industrial De Arvore Vila Do Conde 4480-622, Portugal

**Comment by jn2chang** [comment]
21
CEC Mendelo change request.
A. At their English church "contact us" site:

1. Please remove the line with their evangelist name and phone #.
2. Please update their address to the following:
Address: Rua B 60Zona Industrial De Arvore Vila Do Conde 4480-622, Portugal
3. Please update the Google map as well.
B. At their Chinese church landing site:
1. Please remove the line with with their evangelist's name and phone #.
2. Please update their address to the following:
地址: Rua B 60Zona Industrial De Arvore Vila Do Conde 4480-622, Portugal
3. Please update the Google map as well.

**Comment by jn2chang** [comment]
22
CEC Gran Canaria Change Request:
CEC Gran Canaria church landing site update:
At the English site, please replace the lines on Pastor’s name etc and Contact person’s name etc. with the following two lines, and update the phone numbers:
Evangelists: Ev. Huan Jin, 628-667-979;
	           Ev. Lin Tao Wu, 654-852-708;
Tel#:  628-667-979, 654-852-708
At the Chinese site, please replace the lines on 牧師’s name etc and 聯絡人’s name etc. with the following two lines, and update the phone numbers:
傳道: 金歡 傳道, 628-667-979;
          吳林濤 傳道, 654-852-708;
電話:  628-667-979, 654-852-708

**Comment by jn2chang** [comment]
23
CEC Gran Canaria Change Request:
CEC Gran Canaria church "Contact Us" update:
At the English site, please replace the lines on Pastor’s name etc and Contact person’s name etc. with the following two lines. Please update the telephone #.
Evangelists: Ev. Huan Jin, 628-667-979;
	            Ev. Lin Tao Wu, 654-852-708;
Tel#:  628-667-979, 654-852-708
At the Chinese site, please replace the lines on 牧師’s name etc and 聯絡人’s name etc. with the following two lines. Please update the phone # as well.
傳道: 金歡 傳道, 628-667-979;
          吳林濤 傳道, 654-852-708;
電話:  628-667-979, 654-852-708
